name: run main.py

on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: alpine-latest
    steps:
      - name: pip
        run: python -m pip install --upgrade pip
      
      - name: run
        run: python main.py
